import { NextRequest, NextResponse } from 'next/server';
import { getServerSession } from 'next-auth';
import { authOptions } from '../../auth/[...nextauth]/route';
import { connectToDatabase } from '@/lib/mongodb';
import Presentation from '@/models/Presentation';

export async function POST(req: NextRequest) {
    try {
        const session = await getServerSession(authOptions);
    
        if (!session?.user) {
            return NextResponse.json(
                { message: 'Unauthorized' },
                { status: 401 }
            );
        }
    
        const userId = session.user.id;
        const { prompt, numSlides, language } = await req.json();
    
        // Validate inputs
        if (!prompt) {
            return NextResponse.json(
                { message: 'Prompt is required' },
                { status: 400 }
            );
        }
    
        if (!numSlides || numSlides < 1 || numSlides > 20) {
            return NextResponse.json(
                { message: 'Number of slides must be between 1 and 20' },
                { status: 400 }
            );
        }
    
        // Here you would call your AI service to generate the presentation
        // For now, we'll create a placeholder presentation
    
        // Connect to the database
        await connectToDatabase();
    
        // Create a new presentation
        const presentation = new Presentation({
            title: `AI Presentation - ${new Date().toLocaleDateString()}`,
            description: prompt,
            userId,
            slides: Array(numSlides).fill(null).map((_, index) => ({
                id: `slide-${index + 1}`,
                layouts: [
                    {
                        id: `layout-${index + 1}`,
                        type: 'fixed',
                        elements: [
                            {
                                id: `element-${index + 1}`,
                                type: 'text',
                                content: `Slide ${index + 1} - Content will be generated by AI (prompt: ${prompt})`,
                                position: { x: 50, y: 50 },
                                size: { width: 500, height: 100 },
                                style: { fontSize: '16px' },
                                zIndex: 1,
                            }
                        ],
                        style: {},
                    }
                ],
            })),
            createdAt: Date.now(),
            updatedAt: Date.now(),
        });
    
        await presentation.save();
    
        // TODO: In a real implementation, you would send the prompt to your AI service
        // and then update the presentation with the generated content
    
        return NextResponse.json({
            message: 'Presentation created with AI',
            presentationId: presentation._id,
        });
    } catch (error) {
        console.error('AI presentation creation error:', error);
        return NextResponse.json(
            { message: 'Failed to create presentation with AI' },
            { status: 500 }
        );
    }
} 