import { Theme, ThemeData } from '../types/theme';
import { createNewTheme } from '../constants/defaultTheme';

const createTheme = (id: string, data: ThemeData): Omit<Theme, 'id'> => {
    const theme = createNewTheme({ ...data, name: 'Новая тема' });
    return theme;
};

export const THEME_TEMPLATES: Omit<Theme, 'id'>[] = [
    createTheme('atacama', {
        name: 'Atacama Desert',
        description: 'Warm desert tones with earthy colors',
        colors: {
            primaryAccent: '#E65100',
            slideBackground: '#FFF3E0',
            pageBackground: {
                type: 'color',
                color: '#FBE9E7',
                imageUrl: '',
            },
        },
        typography: {
            headingColor: '#4E342E',
            bodyColor: '#6D4C41',
            headingFont: 'merriweather',
            bodyFont: 'inter',
            headingWeight: 400,
            headingLineHeight: 1.25,
            headingLetterSpacing: 0,
            headingCapitalization: 'none',
            bodyWeight: 400,
            bodyLineHeight: 1.25,
            bodyLetterSpacing: 0,
            bodyCapitalization: 'none',
        },
        design: {
            slide: {
                borderRadius: '8px',
                borderColor: '#E65100',
                shadow: 'sm',
                borderWidth: 'thin',
                imageShape: 'round',
                opacity: 0.9,
            },
            blocks: {
                backgroundColor: '#E65100',
                backgroundBlockFillType: 'fill',
                borderWidth: 'thin',
                shadow: 'sm',
                blockFillColorsType: 'primary',
                blockBackgroundCustomColors: [],
            },
            buttons: {
                buttonColor: '#E65100',
                buttonShape: 'default',
                linkColor: '#E65100',
            },
        },
    }),
    createTheme('ocean-breeze', {
        name: 'Ocean Breeze',
        description: 'Cool blues inspired by the sea',
        colors: {
            primaryAccent: '#0288D1',
            slideBackground: '#E1F5FE',
            pageBackground: {
                type: 'color',
                color: '#B3E5FC',
                imageUrl: '',
            },
        },
        typography: {
            headingColor: '#01579B',
            bodyColor: '#0277BD',
            headingFont: 'poppins',
            bodyFont: 'poppins',
            headingWeight: 400,
            headingLineHeight: 1.25,
            headingLetterSpacing: 0,
            headingCapitalization: 'none',
            bodyWeight: 400,
            bodyLineHeight: 1.25,
            bodyLetterSpacing: 0,
            bodyCapitalization: 'none',
        },
        design: {
            slide: {
                borderRadius: '8px',
                borderColor: '#E65100',
                shadow: 'sm',
                borderWidth: 'thin',
                imageShape: 'round',
                opacity: 0.9,
            },
            blocks: {
                backgroundColor: '#E65100',
                backgroundBlockFillType: 'fill',
                borderWidth: 'thin',
                shadow: 'sm',
                blockFillColorsType: 'primary',
                blockBackgroundCustomColors: [],
            },
            buttons: {
                buttonColor: '#E65100',
                buttonShape: 'default',
                linkColor: '#E65100',
            },
        },
    }),
    createTheme('forest-whisper', {
        name: 'Forest Whisper',
        description: 'Soft greens of a peaceful forest',
        colors: {
            primaryAccent: '#2E7D32',
            slideBackground: '#E8F5E9',
            pageBackground: {
                type: 'color',
                color: '#C8E6C9',
                imageUrl: '',
            },
        },
        typography: {
            headingColor: '#1B5E20',
            bodyColor: '#2E7D32',
            headingFont: 'roboto',
            bodyFont: 'roboto',
            headingWeight: 400,
            headingLineHeight: 1.25,
            headingLetterSpacing: 0,
            headingCapitalization: 'none',
            bodyWeight: 400,
            bodyLineHeight: 1.25,
            bodyLetterSpacing: 0,
            bodyCapitalization: 'none',
        },
        design: {
            slide: {
                borderRadius: '8px',
                borderColor: '#E65100',
                shadow: 'sm',
                borderWidth: 'thin',
                imageShape: 'round',
                opacity: 0.9,
            },
            blocks: {
                backgroundColor: '#E65100',
                backgroundBlockFillType: 'fill',
                borderWidth: 'thin',
                shadow: 'sm',
                blockFillColorsType: 'primary',
                blockBackgroundCustomColors: [],
            },
            buttons: {
                buttonColor: '#E65100',
                buttonShape: 'default',
                linkColor: '#E65100',
            },
        },
    }),
    createTheme('sunset-glow', {
        name: 'Sunset Glow',
        description: 'Vibrant oranges and reds of sunset',
        colors: {
            primaryAccent: '#D84315',
            slideBackground: '#FBE9E7',
            pageBackground: {
                type: 'color',
                color: '#FFCCBC',
                imageUrl: '',
            },
        },
        typography: {
            headingColor: '#BF360C',
            bodyColor: '#E64A19',
            headingFont: 'poppins',
            bodyFont: 'inter',
            headingWeight: 400,
            headingLineHeight: 1.25,
            headingLetterSpacing: 0,
            headingCapitalization: 'none',
            bodyWeight: 400,
            bodyLineHeight: 1.25,
            bodyLetterSpacing: 0,
            bodyCapitalization: 'none',
        },
        design: {
            slide: {
                borderRadius: '8px',
                borderColor: '#E65100',
                shadow: 'sm',
                borderWidth: 'thin',
                imageShape: 'round',
                opacity: 0.9,
            },
            blocks: {
                backgroundColor: '#E65100',
                backgroundBlockFillType: 'fill',
                borderWidth: 'thin',
                shadow: 'sm',
                blockFillColorsType: 'primary',
                blockBackgroundCustomColors: [],
            },
            buttons: {
                buttonColor: '#E65100',
                buttonShape: 'default',
                linkColor: '#E65100',
            },
        },
    }),
    createTheme('minimal-light', {
        name: 'Minimal Light',
        description: 'Clean light theme with blue accents',
        colors: {
            primaryAccent: '#3B82F6',
            slideBackground: '#FFFFFF',
            pageBackground: {
                type: 'color',
                color: '#F3F4F6',
                imageUrl: '',
            },
        },
        typography: {
            headingColor: '#111827',
            bodyColor: '#374151',
            headingFont: 'inter',
            bodyFont: 'inter',
            headingWeight: 400,
            headingLineHeight: 1.25,
            headingLetterSpacing: 0,
            headingCapitalization: 'none',
            bodyWeight: 400,
            bodyLineHeight: 1.25,
            bodyLetterSpacing: 0,
            bodyCapitalization: 'none',
        },
        design: {
            slide: {
                borderRadius: '8px',
                borderColor: '#E5E7EB',
                borderWidth: 'thin',
                shadow: 'sm',
                imageShape: 'round',
                opacity: 1,
            },
            blocks: {
                backgroundColor: '#E65100',
                backgroundBlockFillType: 'fill',
                borderWidth: 'thin',
                shadow: 'sm',
                blockFillColorsType: 'primary',
                blockBackgroundCustomColors: [],
            },
            buttons: {
                buttonColor: '#E65100',
                buttonShape: 'default',
                linkColor: '#E65100',
            },
        },
    }),
    createTheme('minimal-dark', {
        name: 'Minimal Dark',
        description: 'Dark background with bright blue accents',
        colors: {
            primaryAccent: '#2563EB',
            slideBackground: '#1F2937',
            pageBackground: {
                type: 'color',
                color: '#111827',
                imageUrl: '',
            },  
        },
        typography: {
            headingColor: '#F3F4F6',
            bodyColor: '#D1D5DB',
            headingFont: 'inter',
            bodyFont: 'inter',
            headingWeight: 400,
            headingLineHeight: 1.25,
            headingLetterSpacing: 0,
            headingCapitalization: 'none',
            bodyWeight: 400,
            bodyLineHeight: 1.25,
            bodyLetterSpacing: 0,
            bodyCapitalization: 'none',
        },
        design: {
            slide: {
                borderRadius: '8px',
                borderColor: '#374151',
                borderWidth: 'thin',
                shadow: 'sm',
                imageShape: 'round',
                opacity: 0.9,
            },
            blocks: {
                backgroundColor: '#E65100',
                backgroundBlockFillType: 'fill',
                borderWidth: 'thin',
                shadow: 'sm',
                blockFillColorsType: 'primary',
                blockBackgroundCustomColors: [],
            },
            buttons: {
                buttonColor: '#E65100',
                buttonShape: 'default',
                linkColor: '#E65100',
            },
        },
    }),
    createTheme('corporate-blue', {
        name: 'Corporate Blue',
        description: 'Professional theme with subtle blues',
        colors: {
            primaryAccent: '#1D4ED8',
            slideBackground: '#FFFFFF',
            pageBackground: {
                type: 'color',
                color: '#F8FAFC',
                imageUrl: '',
            },
        },
        typography: {
            headingColor: '#1E293B',
            bodyColor: '#334155',
            headingFont: 'roboto',
            bodyFont: 'roboto',
            headingWeight: 400,
            headingLineHeight: 1.25,
            headingLetterSpacing: 0,
            headingCapitalization: 'none',
            bodyWeight: 400,
            bodyLineHeight: 1.25,
            bodyLetterSpacing: 0,
            bodyCapitalization: 'none',
        },
        design: {
            slide: {
                borderRadius: '8px',
                borderColor: '#E65100',
                shadow: 'sm',
                borderWidth: 'thin',
                imageShape: 'round',
                opacity: 0.9,
            },
            blocks: {
                backgroundColor: '#E65100',
                backgroundBlockFillType: 'fill',
                borderWidth: 'thin',
                shadow: 'sm',
                blockFillColorsType: 'primary',
                blockBackgroundCustomColors: [],
            },
            buttons: {
                buttonColor: '#E65100',
                buttonShape: 'default',
                linkColor: '#E65100',
            },
        },
    }),
    createTheme('retro-pop', {
        name: 'Retro Pop',
        description: 'Bright and playful retro colors',
        colors: {
            primaryAccent: '#E91E63',
            slideBackground: '#FCE4EC',
            pageBackground: {
                type: 'color',
                color: '#F8BBD0',
                imageUrl: '',
            },
        },
        typography: {
            headingColor: '#880E4F',
            bodyColor: '#AD1457',
            headingFont: 'lato',
            bodyFont: 'lato',
            headingWeight: 400,
            headingLineHeight: 1.25,
            headingLetterSpacing: 0,
            headingCapitalization: 'none',
            bodyWeight: 400,
            bodyLineHeight: 1.25,
            bodyLetterSpacing: 0,
            bodyCapitalization: 'none',
        },
        design: {
            slide: {
                borderRadius: '8px',
                borderColor: '#E65100',
                shadow: 'sm',
                borderWidth: 'thin',
                imageShape: 'round',
                opacity: 0.9,
            },
            blocks: {
                backgroundColor: '#E65100',
                backgroundBlockFillType: 'fill',
                borderWidth: 'thin',
                shadow: 'sm',
                blockFillColorsType: 'primary',
                blockBackgroundCustomColors: [],
            },
            buttons: {
                buttonColor: '#E65100',
                buttonShape: 'default',
                linkColor: '#E65100',
            },
        },
    }),
    createTheme('neon-night', {
        name: 'Neon Night',
        description: 'Dark theme with glowing neon accents',
        colors: {
            primaryAccent: '#00E5FF',
            slideBackground: '#263238',
            pageBackground: {
                type: 'color',
                color: '#000000',
                imageUrl: '',
            },
        },
        typography: {
            headingColor: '#E0E0E0',
            bodyColor: '#B0BEC5',
            headingFont: 'poppins',
            bodyFont: 'poppins',
            headingWeight: 400,
            headingLineHeight: 1.25,
            headingLetterSpacing: 0,
            headingCapitalization: 'none',
            bodyWeight: 400,
            bodyLineHeight: 1.25,
            bodyLetterSpacing: 0,
            bodyCapitalization: 'none',
        },
        design: {
            slide: {
                borderRadius: '8px',
                borderColor: '#00E5FF',
                borderWidth: 'thin',
                shadow: 'md',
                imageShape: 'round',
                opacity: 1,
            },
            blocks: {
                backgroundColor: '#E65100',
                backgroundBlockFillType: 'fill',
                borderWidth: 'thin',
                shadow: 'sm',
                blockFillColorsType: 'primary',
                blockBackgroundCustomColors: [],
            },
            buttons: {
                buttonColor: '#E65100',
                buttonShape: 'default',
                linkColor: '#E65100',
            },
        },
    }),
    createTheme('elegant-purple', {
        name: 'Elegant Purple',
        description: 'Refined look with purple accents',
        colors: {
            primaryAccent: '#8E24AA',
            slideBackground: '#F3E5F5',
            pageBackground: {
                type: 'color',
                color: '#EDE7F6',
                imageUrl: '',
            },
        },
        typography: {
            headingColor: '#4A148C',
            bodyColor: '#6A1B9A',
            headingFont: 'merriweather',
            bodyFont: 'inter',
            headingWeight: 400,
            headingLineHeight: 1.25,
            headingLetterSpacing: 0,
            headingCapitalization: 'none',
            bodyWeight: 400,
            bodyLineHeight: 1.25,
            bodyLetterSpacing: 0,
            bodyCapitalization: 'none',
        },
        design: {
            slide: {
                borderRadius: '8px',
                borderColor: '#E65100',
                shadow: 'sm',
                borderWidth: 'thin',
                imageShape: 'round',
                opacity: 0.9,
            },
            blocks: {
                backgroundColor: '#E65100',
                backgroundBlockFillType: 'fill',
                borderWidth: 'thin',
                shadow: 'sm',
                blockFillColorsType: 'primary',
                blockBackgroundCustomColors: [],
            },
            buttons: {
                buttonColor: '#E65100',
                buttonShape: 'default',
                linkColor: '#E65100',
            },
        },
    }),
];
