const ERROR_CODES = {
    SUCCESS: 0,
    INCORRECT_INVOICE: 10,
    INCORRECT_ACCOUNT_ID: 11,
    INCORRECT_AMOUNT: 12,
    PAYMENT_NOT_ACCEPTED: 13,
    PAYMENT_EXPIRED: 20,
};

export default ERROR_CODES;
